- name: reform certificate
  shell: awk '$1=$1' ORS='\\n' {{ elb_certificate_certificate_file }}
  register: elb_certificate_certificate

- name: reform certificate key
  shell: awk '$1=$1' ORS='\\n' {{ elb_certificate_key_file }}
  register: elb_certificate_key

- name: Send request to API
  uri:
    url: "{{ AUTH_URL_ELB_CERTIFICATE }}"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'roles/elb_certificate_create/templates/request.json.j2')|to_json }}" 
  register: elbcertificate

- debug:
    msg: "{{ elbcertificate }}"

