- name: Request delete zonerecord  from  API
  uri:
    url: "{{ AUTH_URL_DNS }}/zones/{{ zoneid }}/recordsets/{{ zonerecordid}}"
    method: DELETE
    return_content: yes 
    validate_certs: yes
    status_code: 200,201,202,203
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  when: zonerecordid is defined
  register: zonerecord

- debug: var=zonerecord.json
  when: zonerecord is defined
