- include_vars: _secrets.yml

- name: create timestamp
  shell:  LC_ALL=en date +"%a, %d %b %Y %T %z"
  register: sigdate

- name: create signature
  shell: echo -en "GET\n\n\n\nx-amz-date:{{ sigdate.stdout }}\n/" | openssl sha1 -hmac {{ EC2_SECRET_KEY }} -binary | base64
  register: signature

- name: curl request
  command: 'curl -H "Authorization: AWS {{ EC2_ACCESS_KEY }}:{{ signature.stdout }}" -H "x-amz-date: {{ sigdate.stdout }}" {{ EC2_URL }}'
  register: curlresponse

- name: xmllint output
  shell: echo '{{ curlresponse.stdout }}' | xmllint --format -
  register: xmlout

- debug:
    msg: "{{ xmlout.stdout_lines }}"
