- name: Request volumes list from  API
  uri:
    url: "{{ AUTH_URL_EVS }}/volumes/{{ evs_id }}"
    method: GET
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: volume

- debug:
    msg: "{{ volume.json }}"

