- include_vars: _elb_secrets.yml

- name: Send request to API
  uri:
    url: "{{ AUTH_URL_ELB }}"
    method: GET
    follow_redirects: all
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: elblist

- debug:
    msg: "{{ elblist }}"

