- name: Request secgroup list with search criteria from API
  uri:
    url: "{{ AUTH_URL_VPC }}/security-groups?vpc_id={{ vpc_id }}"
    method: GET
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: secgrouplistvpc
  when: vpc_id is defined

- name: Request secgroup list from API
  uri:
    url: "{{ AUTH_URL_VPC }}/security-groups"
    method: GET
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: secgrouplist
  when: vpc_id is not defined

- debug:
    msg: "{{ secgrouplistvpc.json }}"
  when: vpc_id is defined

- debug:
    msg: "{{ secgrouplist.json }}"
  when: vpc_id is not defined

