- name: Send request to API
  uri:
    url: "{{ AUTH_URL_ELB_LISTENER }}/{{ elb_listener_id}}"
    method: DELETE
    follow_redirects: all
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: elblistener

- debug:
    msg: "{{ elblistener }}"

