- name: Send request to API
  uri:
    url: "{{ AUTH_URL_VPC }}/vpcs/{{ vpc_id}}"
    method: DELETE
    body_format: raw
    follow_redirects: all
    return_content: yes 
    validate_certs: yes
    status_code: 200,201,202,203,204
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: vpc

- debug:
    msg: "{{ vpc }}"

