- include_vars: _elb_secrets.yml

- name: Send request to API
  uri:
    url: "{{ AUTH_URL_ELB_LISTENER }}/{{ elb_listener_id}}/members?limit=10&marker=0"
    method: GET
    follow_redirects: all
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: elblistener

- debug:
    msg: "{{ elblistener }}"

