- include_vars: _secrets.yml

- name: create timestamp
  shell:  LC_ALL=en date +"%a, %d %b %Y %T %z"
  register: sigdate


- name: create signature
  shell: echo -en "PUT\n\n\n\nx-amz-date:{{ sigdate.stdout }}\n/{{ bucket }}/{{ object }}" | openssl sha1 -hmac {{ EC2_SECRET_KEY }} -binary | base64
  register: signature

- name: curl request
  command: 'curl -X PUT -H "Authorization: AWS {{ EC2_ACCESS_KEY }}:{{ signature.stdout }}" -H "x-amz-date: {{ sigdate.stdout }}" -T {{ object }} {{ EC2_URL }}/{{ bucket }}/{{ object }}'
  register: curlresponse

- debug:
    msg: "{{ curlresponse.stdout_lines }}"
