- include_vars: _secrets.yml

- name: Request services list from AUTH API
  uri:
    url: "{{ AUTH_URL_KEYSTONE }}/services"
    method: GET
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: servicelist

- debug:
    msg: "{{ servicelist.json }}"

