- name: Send request to API
  uri:
    url: "{{ AUTH_URL_ELB_CERTIFICATE }}"
    method: GET
    follow_redirects: all
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
  register: elbcertificate

- debug:
    msg: "{{ elbcertificate }}"

