- include_vars: _secrets.yml

- name: Send request to API
  uri:
    url: "{{ AUTH_URL_CLOUDIMAGES }}/action"
    method: POST
    body_format: raw
    follow_redirects: all
    return_content: yes 
    validate_certs: yes
    HEADER_Content-Type: "application/json"
    HEADER_X-Auth-Token: "{{ token['x_subject_token'] }}"
    body: "{{ lookup('template', 'roles/image_create/templates/request.json.j2')|to_json }}" 
  register: image_create

- debug:
    msg: "{{ image_create }}"

